[package]
name = "blur_plugin"
version = "0.1.1"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
log = { workspace = true}
serde = { workspace = true}
serde_json = { workspace = true}
env_logger = { workspace = true}
plugin_lib = { workspace = true}

